package com.tdhctf.mob01.crypto

import com.tdhctf.mob01.BuildConfig

/**
 * The per-startup challenge KEY (generated by startup.sh into ./keys/mob-01.key)
 * is injected at build time into BuildConfig via Gradle property/file.
 *
 * This is distinct from the app secret used to decrypt the embedded flag blob.
 */
internal object ChallengeKeyVault {
    fun revealChallengeKey(): String {
        val key = BuildConfig.MOB01_CHALLENGE_KEY
        require(key.isNotBlank() && key != "MOB01_KEY_NOT_SET") { "Challenge key not set" }
        return key
    }
}


