package com.tdhctf.mob02.crypto

import com.tdhctf.mob02.BuildConfig

/**
 * The per-startup challenge KEY (generated by startup.sh into ./keys/mob-02.key)
 * is injected at build time into BuildConfig via Gradle property/file.
 *
 * This is distinct from the JWT signing secret used for token verification.
 */
internal object ChallengeKeyVault {
    fun revealChallengeKey(): String {
        val key = BuildConfig.MOB02_CHALLENGE_KEY
        require(key.isNotBlank() && key != "MOB02_KEY_NOT_SET") { "Challenge key not set" }
        return key
    }
}


