#!/usr/bin/env python3
"""
Broken Encryption Key - CRYPTO-02-MEDIUM
RSA with close primes vulnerable to Fermat's factorization attack
"""

import os
import random

def bytes_to_long(b: bytes) -> int:
    return int.from_bytes(b, "big")


def is_probable_prime(n: int, rounds: int = 12) -> bool:
    """Miller-Rabin probable prime test (good enough for CTF generators)."""
    if n < 2:
        return False
    small_primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
    for p in small_primes:
        if n == p:
            return True
        if n % p == 0:
            return False

    # write n-1 = d * 2^s
    d = n - 1
    s = 0
    while d % 2 == 0:
        d //= 2
        s += 1

    for _ in range(rounds):
        a = random.randrange(2, n - 1)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _r in range(s - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


def gen_prime(bits: int) -> int:
    while True:
        n = random.getrandbits(bits)
        n |= (1 << (bits - 1))  # ensure top bit
        n |= 1  # odd
        if is_probable_prime(n):
            return n


def generate_close_primes(bits: int = 512) -> tuple[int, int]:
    """Generate two primes that are close to each other (Fermat-friendly)."""
    p = gen_prime(bits)
    # Keep offset small so Fermat factoring is fast for players
    offset = random.randrange(10_000, 200_000, 2)
    q = p + offset
    while not is_probable_prime(q):
        offset += 2
        q = p + offset
    return p, q

def main():
    # Get the challenge key from environment (generated by entrypoint.sh)
    if 'CHALLENGE_KEY' in os.environ:
        challenge_key = os.environ['CHALLENGE_KEY']
    else:
        challenge_key = "offline-default-crypto02"
    
    # Constant flag (deployment key is separate and must be recovered from the decrypted plaintext)
    flag = "TDHCTF{vault_breach_decrypted}"
    
    # Encrypt a plaintext that contains BOTH values (same pattern as other challenges)
    message = f"KEY:{challenge_key}\nFLAG:{flag}\n"
    
    print("[+] Generating RSA keys with close primes...")
    
    # Generate close primes for Fermat's attack
    p, q = generate_close_primes(512)
    n = p * q
    e = 65537
    
    # Encrypt the message
    m = bytes_to_long(message.encode())
    c = pow(m, e, n)
    
    # Calculate phi for verification
    phi = (p - 1) * (q - 1)
    d = pow(e, -1, phi)
    
    # Verify encryption/decryption works
    m_test = pow(c, d, n)
    assert m == m_test, "Encryption/decryption verification failed!"
    
    # Write output file
    output_path = '/challenge-files/crypto-02-vault-breach/encrypted_vault.txt'
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("=== BROKEN ENCRYPTION KEY ===\n")
        f.write("We recovered this encrypted message from the vault's logs.\n")
        f.write("Our cryptanalyst noticed something odd about the encryption key...\n")
        f.write("The modulus seems unusually vulnerable. Something about the primes?\n")
        f.write("\n")
        f.write("RSA PARAMETERS:\n")
        f.write(f"n = {n}\n")
        f.write(f"e = {e}\n")
        f.write("\n")
        f.write(f"ENCRYPTED MESSAGE:\n")
        f.write(f"c = {c}\n")
        f.write("\n")
        f.write("HINT: When primes are too close, factorization becomes easier.\n")
        f.write("HINT: Look into Fermat's factorization method.\n")
    
    # Also save private key for debugging (not accessible to players)
    debug_path = '/app/private_key.txt'
    with open(debug_path, 'w') as f:
        f.write(f"p = {p}\n")
        f.write(f"q = {q}\n")
        f.write(f"d = {d}\n")
        f.write(f"p - q = {abs(p - q)}\n")
    
    print(f"[+] Challenge file generated: {output_path}")
    print(f"[+] Public key (n, e): ({n}, {e})")
    print(f"[+] Ciphertext: {c}")
    print(f"[+] Prime difference: {abs(p - q)}")
    print(f"[+] Challenge Key: {challenge_key}")
    print(f"[+] Flag: {flag}")

if __name__ == '__main__':
    main()

